---
- name: Remove all Tenants
  hosts: lb
  connection: httpapi
  gather_facts: false

  vars:
    ansible_httpapi_password: "{{ ansible_password }}"
    ansible_network_os: f5networks.f5_bigip.bigip
    ansible_httpapi_use_ssl: yes
    ansible_httpapi_validate_certs: no
    ansible_httpapi_port: "{{ server_port }}"

  tasks:

    # # - name: Generate random IP addresses
    # - name: Generate random IP addresses
    #   set_fact:
    #     app_ips: "{{ app_ips | default([]) + ['10.0.' ~ (1 + (254 | random)) ~ '.' ~ (1 + (254 | random))] }}"
    #   loop: "{{ range(100) | list }}"

    - name: Remove all tenants - AS3
      bigip_as3_deploy:
        tenant: all
        state: absent