---
- name: AS3 100s of Apps
  hosts: lb
  connection: httpapi
  gather_facts: false

  vars:
    ansible_httpapi_password: "{{ ansible_password }}"
    ansible_network_os: f5networks.f5_bigip.bigip
    ansible_httpapi_use_ssl: yes
    ansible_httpapi_validate_certs: no
    ansible_httpapi_port: "{{ server_port }}"
    ansible_httpapi_use_proxy: no


  tasks:

    # # - name: Generate random IP addresses
    # - name: Generate random IP addresses
    #   set_fact:
    #     app_ips: "{{ app_ips | default([]) + ['10.0.' ~ (1 + (254 | random)) ~ '.' ~ (1 + (254 | random))] }}"
    #   loop: "{{ range(100) | list }}"

    - name: CREATE AS3 JSON BODY
      set_fact:
        as3_app_body: "{{ lookup('template', 'j2/multi-tenant.j2', split_lines=False) }}"

    - name: PUSH AS3 Template
      f5networks.f5_bigip.bigip_as3_deploy:
        content: "{{ lookup('template','j2/multi-tenant.j2', split_lines=False) }}"
      timeout: 180
