---
- name: Copy Inventory File For Tenant Creation
  hosts: bastion-backup
  tasks:

    - name: use find to get the files list which you want to copy/fetch
      ansible.builtin.find: 
        paths: /tmp/
        patterns: "inventory_*.json"
      register: file_2_fetch

    - name: use fetch to get the files
      ansible.builtin.fetch:
        src: "{{ item.path }}"
        dest: /tmp/
        flat: yes
      with_items: "{{ file_2_fetch.files }}"

    - name: Import Information From JSON File
      ansible.builtin.set_fact:
        inventory: "{{ lookup('file',item) | from_json }}"
      with_fileglob: "/tmp/inventory_*.json"
      delegate_to: localhost

    - debug:
        var: item
      with_items: "{{ inventory.vlans }}"