---
- name: Copy Inventory File For Tenant Creation
  hosts: bastion-backup
  tasks:

    - name: use find to get the files list which you want to copy/fetch
      ansible.builtin.find: 
        paths: /tmp/
        patterns: "inventory_*.json"
      register: file_2_fetch

    - name: use fetch to get the files
      ansible.builtin.fetch:
        src: "{{ item.path }}"
        dest: /tmp/
        flat: yes
      with_items: "{{ file_2_fetch.files }}"


- name: Test
  hosts: velos
  connection: httpapi
  gather_facts: false

  vars:
    ansible_httpapi_password: "{{ ansible_password }}"
    ansible_network_os: "f5networks.f5os.f5os"
    ansible_httpapi_use_ssl: true
    ansible_httpapi_use_proxy: false
    ansible_httpapi_validate_certs: false
    ansible_httpapi_port: "{{ server_port }}"
    ansible_command_timeout: 1800
    persistent_log_messages: tenant_info.true

  tasks:

    - name: GET Management-VLAN if Defined
      ansible.builtin.uri:
        url: 'https://{{ ansible_host }}:8888/restconf/data/f5-tenants:tenants/tenant=cdsn7-i10800-test1/config/f5-tenant-mgmt-vlan:mgmt-vlan'
        method: GET
        status_code: 
          - 200
          - 201
          - 202 
          - 204
        timeout: 300
        headers:
          Content-Type: "application/yang-data+json"
        force_basic_auth: true
        user: "{{ ansible_user }}"
        password: "{{ ansible_password }}"
        validate_certs: false
      delegate_to: localhost