---
- name: Create F5OS Tenant
  hosts: velos
  connection: httpapi
  gather_facts: false

  vars:
    ansible_httpapi_password: "{{ ansible_password }}"
    ansible_network_os: "f5networks.f5os.f5os"
    ansible_httpapi_use_ssl: true
    ansible_httpapi_use_proxy: false
    ansible_httpapi_validate_certs: false
    ansible_httpapi_port: "{{ server_port }}"
    ansible_command_timeout: 1800
    persistent_log_messages: tenant_info.true
    partition_name: DemoPartition
    cpu_cores: 4
    memory: "{{ ( 3.5 * 1024 * cpu_cores ) + 512 | int }}"
    mgmt_vlan: 3007
    tenant_name: "cdsn7-i10800-test1"
    #tenant_name: "test"

  tasks:

    - name: before
      ansible.builtin.uri:
        url: "https://{{ ansible_host }}:8888/restconf/data/f5-tenants:tenants/tenant={{ tenant_name }}"
        method: GET
        status_code: 200
        return_content: true
        headers:
          Content-Type: "application/yang-data+json"
        timeout: 300
        force_basic_auth: true
        user: "{{ ansible_user }}"
        password: "{{ ansible_password }}"
        validate_certs: false
      delegate_to: localhost
      register: do_result3

    - name: running state
      ansible.builtin.uri:
        url: "https://{{ ansible_host }}:8888/restconf/data/f5-tenants:tenants/tenant={{ tenant_name }}/config/running-state"
        method: PATCH
        status_code: 
          - 200
          - 202
        timeout: 300
        body_format: json
        headers:
          Content-Type: "application/yang-data+json"
        body:
          running-state: "provisioned"
        force_basic_auth: true
        user: "{{ ansible_user }}"
        password: "{{ ansible_password }}"
        validate_certs: false
      delegate_to: localhost
      register: do_result

    - name: mgmt-vlan
      ansible.builtin.uri:
        url: "https://{{ ansible_host }}:8888/restconf/data/f5-tenants:tenants/tenant={{ tenant_name }}/config/f5-tenant-mgmt-vlan:mgmt-vlan"
        method: PATCH
        status_code: 
          - 200
          - 202
        timeout: 300
        return_content: true
        headers:
          Content-Type: "application/yang-data+json"
        body:
          f5-tenant-mgmt-vlan:mgmt-vlan: 3014
        force_basic_auth: true
        user: "{{ ansible_user }}"
        password: "{{ ansible_password }}"
        validate_certs: false
      delegate_to: localhost
      register: do_result

    - debug:
        var: do_result

    - name: after
      ansible.builtin.uri:
        url: "https://{{ ansible_host }}:8888/restconf/data/f5-tenants:tenants/tenant={{ tenant_name }}"
        method: GET
        status_code: 200
        return_content: true
        headers:
          Content-Type: "application/yang-data+json"
        timeout: 300
        force_basic_auth: true
        user: "{{ ansible_user }}"
        password: "{{ ansible_password }}"
        validate_certs: false
      delegate_to: localhost
      register: do_result2

    - debug:
        var: do_result2