---
- name: Wait for Restored F5 to Come Online
  hosts: velos-lb
  connection: httpapi
  gather_facts: false

  vars:
    ansible_httpapi_password: "{{ ansible_password }}"
    ansible_network_os: f5networks.f5_bigip.bigip
    ansible_httpapi_use_ssl: yes
    ansible_httpapi_validate_certs: no
    ansible_httpapi_port: "{{ server_port }}"
    ansible_command_timeout: 300
    ansible_httpapi_use_proxy: no
  tasks:

    - name: Get Failover State - Module
      f5networks.f5_bigip.bigip_command:
        commands: show sys failover
      register: f5_online
      until: 
        - "'Active' in f5_online.stdout[0]"
        - "'green' in f5_online.stdout[0]"
      retries: 40
      delay: 30
