---
- name: Copy Inventory File For Tenant Creation
  hosts: bastion-backup
  tasks:

    - name: use find to get the files list which you want to copy/fetch
      ansible.builtin.find: 
        paths: /tmp/
        patterns: "inventory_*.json"
      register: file_2_fetch

    - name: use fetch to get the files
      ansible.builtin.fetch:
        src: "{{ item.path }}"
        dest: /tmp/
        flat: yes
      with_items: "{{ file_2_fetch.files }}"


- name: Test
  hosts: velos
  connection: httpapi
  gather_facts: false

  vars:
    ansible_httpapi_password: "{{ ansible_password }}"
    ansible_network_os: "f5networks.f5os.f5os"
    ansible_httpapi_use_ssl: true
    ansible_httpapi_use_proxy: false
    ansible_httpapi_validate_certs: false
    ansible_httpapi_port: "{{ server_port }}"
    ansible_command_timeout: 1800
    persistent_log_messages: tenant_info.true

  tasks:

    - name: Import Information From JSON File
      ansible.builtin.set_fact:
        inventory: "{{ lookup('file',item) | from_json }}"
      with_fileglob: "/tmp/inventory_*.json"
      delegate_to: localhost

    # - name: debug output
    #   ansible.builtin.debug:
    #     var: inventory

    - name: Collect interface and vlan information on F5OS device
      f5networks.f5os.f5os_device_info:
        gather_subset:
          - tenant-images
          - vlans 
      register: tenant_info

    - name: GET Management-VLAN if Defined
      ansible.builtin.uri:
        url: 'https://{{ ansible_host }}:8888/restconf/data/f5-tenants:tenants/tenant={{ inventory.devices[0].hostname.split(".")[0] }}'
        method: GET
        status_code: 
          - 200
          - 201
          - 202 
          - 204
        timeout: 300
        headers:
          Content-Type: "application/yang-data+json"
        force_basic_auth: true
        user: "{{ ansible_user }}"
        password: "{{ ansible_password }}"
        validate_certs: false
      delegate_to: localhost


    - name: Set Management-VLAN if Defined
      ansible.builtin.uri:
        url: 'https://{{ ansible_host }}:8888/restconf/data/f5-tenants:tenants/tenant={{ inventory.devices[0].hostname.split(".")[0] }}/config/f5-tenant-mgmt-vlan:mgmt-vlan'
        method: PUT
        status_code: 
          - 200
          - 201
          - 202 
          - 204
        timeout: 300
        body_format: json
        headers:
          Content-Type: "application/yang-data+json"
        body:
          f5-tenant-mgmt-vlan:mgmt-vlan: "{{ mgmt_vlan }}"
        force_basic_auth: true
        user: "{{ ansible_user }}"
        password: "{{ ansible_password }}"
        validate_certs: false
      when: mgmt_vlan is defined
      register: response
      changed_when: response.status == 201
      delegate_to: localhost

    - name: GET Management-VLAN if Defined
      ansible.builtin.uri:
        url: 'https://{{ ansible_host }}:8888/restconf/data/f5-tenants:tenants/tenant={{ inventory.devices[0].hostname.split(".")[0] }}'
        method: GET
        status_code: 
          - 200
          - 201
          - 202 
          - 204
        timeout: 300
        headers:
          Content-Type: "application/yang-data+json"
        force_basic_auth: true
        user: "{{ ansible_user }}"
        password: "{{ ansible_password }}"
        validate_certs: false
      delegate_to: localhost