---

- name: Copy Inventory File For Tenant Creation
  hosts: bastion-backup
  tasks:

    - name: use find to get the files list which you want to copy/fetch
      ansible.builtin.find: 
        paths: /tmp/
        patterns: "inventory_*.json"
      register: file_2_fetch

    - name: use fetch to get the files
      ansible.builtin.fetch:
        src: "{{ item.path }}"
        dest: /tmp/
        flat: yes
      with_items: "{{ file_2_fetch.files }}"


- name: Create F5OS Tenant
  hosts: velos
  connection: httpapi
  gather_facts: false

  vars:
    ansible_httpapi_password: "{{ ansible_password }}"
    ansible_network_os: "f5networks.f5os.f5os"
    ansible_httpapi_use_ssl: true
    ansible_httpapi_use_proxy: false
    ansible_httpapi_validate_certs: false
    ansible_httpapi_port: 8888
    ansible_command_timeout: 1800
    persistent_log_messages: tenant_info.true
    partition_name: DemoPartition
    cpu_cores: 4
    memory: "{{ ( 3.5 * 1024 * cpu_cores ) + 512 | int }}"
    mgmt_ip: 192.170.14.85
    mgmt_sn_cidr: 24
    mgmt_gw: 192.170.14.1
    mgmt_vlan: 3007


  tasks:

    # - name: debug output
    #   ansible.builtin.debug:
    #     msg: "{{ memory |int }}"

    - name: Import Information From JSON File
      ansible.builtin.set_fact:
        inventory: "{{ lookup('file',item) | from_json }}"
      with_fileglob: "/tmp/inventory_*.json"
      delegate_to: localhost

    # - name: debug output
    #   ansible.builtin.debug:
    #     var: inventory

    - name: Collect interface and vlan information on F5OS device
      f5networks.f5os.f5os_device_info:
        gather_subset:
          - tenant-images
          - vlans 
      register: tenant_info

    # - name: debug output
    #   ansible.builtin.debug:
    #     var: tenant_info

    - name: Create F5 Tenant
      f5networks.f5os.f5os_tenant:
        name: '{{ inventory.devices[0].hostname.split(".")[0] }}'
        image_name: "{{ tenant_info.tenant_images[0].name }}"
        nodes:
          - 1
        mgmt_ip: "{{ mgmt_ip }}"
        mgmt_prefix: "{{ mgmt_sn_cidr }}"
        mgmt_gateway: "{{ mgmt_gw }}"
        vlans: "{{ tenant_info.vlans[0].vlan_id }}"
        cpu_cores: "{{ cpu_cores }}"
        memory: "{{ memory |int }}"
        cryptos: enabled
        virtual_disk_size: "{{ disk_size | default('120') }}"
        running_state: configured

    - name: Set Management-VLAN if Defined
      ansible.builtin.uri:
        url: "https://{{ ansible_host }}:8888/restconf/data/f5-tenants:tenants/tenant={{ tenant_name }}/config/f5-tenant-mgmt-vlan:mgmt-vlan"
        method: PUT
        status_code: 
          - 200
          - 201
        timeout: 300
        body_format: json
        headers:
          Content-Type: "application/yang-data+json"
        body:
          f5-tenant-mgmt-vlan:mgmt-vlan: "{{ mgmt_vlan }}"
        force_basic_auth: true
        user: "{{ ansible_user }}"
        password: "{{ ansible_password }}"
        validate_certs: false
      when: mgmt_vlan is defined
      delegate_to: localhost

    - name: Start F5 Tenant
      f5networks.f5os.f5os_tenant:
        name: '{{ inventory.devices[0].hostname.split(".")[0] }}'
        running_state: deployed
