---

- name: Copy Inventory File For Tenant Creation
  hosts: bastion-backup
  tasks:

    - name: use find to get the files list which you want to copy/fetch
      ansible.builtin.find: 
        paths: /tmp/
        patterns: "inventory_*.json"
      register: file_2_fetch

    - name: use fetch to get the files
      ansible.builtin.fetch:
        src: "{{ item.path }}"
        dest: /tmp/
        flat: yes
      with_items: "{{ file_2_fetch.files }}"


- name: Create F5OS Tenant
  hosts: velos
  connection: httpapi
  gather_facts: false

  vars:
    ansible_httpapi_password: "{{ ansible_password }}"
    ansible_network_os: "f5networks.f5os.f5os"
    ansible_httpapi_use_ssl: true
    ansible_httpapi_use_proxy: false
    ansible_httpapi_validate_certs: false
    ansible_httpapi_port: "{{ server_port }}"
    ansible_command_timeout: 1800
    persistent_log_messages: true
    partition_name: DemoPartition

  tasks:

    - name: Import Information From JSON File
      ansible.builtin.set_fact:
        inventory: "{{ lookup('file',item) | from_json }}"
      with_fileglob: "/tmp/inventory_*.json"
      delegate_to: localhost

    - name: debug output
      ansible.builtin.debug:
        var: inventory

    - name: Collect interface and vlan information on F5OS device
      f5os_device_info:
        gather_subset:
          - tenant-images
          - vlans 
      register: tenant_info

    - name: debug output
      ansible.builtin.debug:
        var: tenant_info

    # - name: Create tenant 
    #   f5networks.f5os.f5os_tenant:
    #     name: automation-test
    #     image_name: BIGIP-17.5.0-0.0.15.ALL-F5OS.qcow2.zip.bundle
    #     nodes:
    #       - 1
    #     mgmt_ip: 10.10.10.10
    #     mgmt_prefix: 24
    #     mgmt_gateway: 10.10.10.1
    #     vlans: [245]
    #     cpu_cores: 2
    #     memory: 4096
    #     cryptos: disabled
    #     virtual_disk_size: 120
    #     running_state: deployed