---

- name: Copy Inventory File For Tenant Creation
  hosts: bastion-backup
  tasks:
    - name: Copy from Local to Remote location
      ansible.builtin.fetch:
       src: "{{ item }}"
       dest: "{{ item }}"
       flat: yes
      with_fileglob: "/tmp/inventory_*.json"

- name: Create F5OS Tenant
  hosts: velos
  connection: httpapi
  gather_facts: false

  vars:
    ansible_httpapi_password: "{{ ansible_password }}"
    ansible_network_os: f5networks.f5_bigip.bigip
    ansible_httpapi_use_ssl: yes
    ansible_httpapi_validate_certs: no
    ansible_httpapi_port: "{{ server_port }}"
    ansible_command_timeout: 300
    ansible_httpapi_use_proxy: no

  tasks:

    - name: Import Information From JSON File
      ansible.builtin.set_fact:
        inventory: "{{ lookup('file','item') | from_json }}"
      with_fileglob: "/tmp/inventory_*.json"
