---
- name: GRAB F5 FACTS
  hosts: lb
  connection: local
  gather_facts: false

  tasks:
    - name: COLLECT BIG-IP FACTS
      f5networks.f5_modules.bigip_device_info:
        gather_subset:
          - system-info
        provider:
          server: "{{ ansible_host }}"
          user: "{{ ansible_user }}"
          password: "{{ ansible_password }}"
          server_port: "{{ server_port }}"
          no_f5_teem: yes
          validate_certs: false
      register: device_facts

    - name: DISPLAY COMPLETE BIG-IP SYSTEM INFORMATION
      debug:
        var: device_facts

    - name: DISPLAY ONLY THE VERSION
      debug:
        var: device_facts['system_info']['product_version']
  
    - name: DISPLAY THE HARDWARE VERSION
      debug:
        var: device_facts['system_info']['marketing_name']

    - name: DISPLAY THE CPU MODEL
      debug:
        var: item.model
      with_items: "{{ device_facts['system_info']['hardware_information'] }}"
      when: 
      - item.type is defined
      - "'base-board' in item.type"
      - "'cpus' in item.name"

    - name: DISPLAY THE CPU Cores
      debug:
        var: item.versions[1].version
      with_items: "{{ device_facts['system_info']['hardware_information'] }}"
      when: 
      - item.type is defined
      - "'base-board' in item.type"
      - "'cpus' in item.name"

    # - name: DISPLAY THE CPU MODEL
    #   debug:
    #     var: item
    #   with_items: device_facts['system_info']['hardware_information']
    #   when: "{{item.type}} == baseboard"