---
- name: GRAB F5 FACTS
  hosts: lb
  connection: local
  gather_facts: false

  tasks:
    - name: COLLECT BIG-IP FACTS
      f5networks.f5_modules.bigip_device_info:
        gather_subset:
          - devices
        provider:
          server: "{{ ansible_host }}"
          user: "{{ ansible_user }}"
          password: "{{ ansible_password }}"
          server_port: "{{ server_port }}"
          no_f5_teem: yes
          validate_certs: false
      register: device_facts

    - name: Set BIG-IP Information in Variables
      ansible.builtin.debug:
        var: device_facts

    - name: Set BIG-IP Information in Variables
      ansible.builtin.debug:
        var: device_facts['devices'][0]['name']

    - name: Set BIG-IP Information in Variables
      ansible.builtin.debug:
        var: device_facts['devices'][0]['management_address']