---
- name: Ansible Cleanup Files
  hosts: bastion-backup

  tasks:

    - name: Find UCS Files
      ansible.builtin.find: 
        paths: /tmp/
        patterns: "*.ucs"
      register: UCS_fetch

    - name: Remove JSON Files
      ansible.builtin.file:
        path: "{{ item.path }}"
        state: absent
      with_items: "{{ UCS_fetch.files }}"

    - name: Find JSON Files
      ansible.builtin.find: 
        paths: /tmp/
        patterns: "*.json"
      register: JSON_fetch

    - name: Remove JSON Files
      ansible.builtin.file:
        path: "{{ item.path }}"
        state: absent
      with_items: "{{ JSON_fetch.files }}"
