---
- name: GRAB F5 FACTS
  hosts: lb
  connection: local
  gather_facts: false

  tasks:

    - name: Set Provider
      ansible.builtin.set_fact:
        provider:
          server: "{{ ansible_host }}"
          user: "{{ ansible_user }}"
          password: "{{ ansible_password }}"
          server_port: "{{ server_port }}"
          no_f5_teem: true
          validate_certs: false

    - name: COLLECT BIG-IP FACTS
      f5networks.f5_modules.bigip_device_info:
        gather_subset:
          - system-info
          - devices
          - vlans
          - self-ips
          - trunks
          - provision-info
          - sync-status
          - management-routes
        provider: "{{ provider }}"
      register: inventory_info

    - name: "Copy Inventory_Info Variable to Execution Environment File"
      ansible.builtin.copy:
        content: "{{ inventory_info | to_nice_json }}"
        dest: "/tmp/inventory_{{ inventory_hostname }}.json"
        mode: '0755'

    - name: Stop BIGSTART to Disable Node
      f5networks.f5_modules.bigip_command:
        commands: >
          run /util bash -c "bigstart stop"
        provider: "{{ provider }}"
      register: stop_task
      ignore_errors: true

- name: Ansible Copy File
  hosts: bastion-backup
  tasks:
    - name: Copy from Local to Remote location
      ansible.builtin.copy:
        src: "{{ item }}"
        dest: "{{ item }}"
        mode: '0755'
      with_fileglob: "/tmp/inventory_*.json"
