---

- name: Copy Inventory File For Tenant Creation
  hosts: bastion-backup
  tasks:

    - name: Use find to get the files list which you want to copy/fetch
      ansible.builtin.find:
        paths: /tmp/
        patterns: "*.ucs"
      register: ucs_fetch

    - name: Use fetch to get the files # NEED TO FIX FOR SPECIFIC UCS FILE
      ansible.builtin.fetch:
        src: "{{ item.path }}"
        dest: /tmp/
        flat: true
      with_items: "{{ ucs_fetch.files }}"


- name: Restore UCS to Destination
  hosts: velos-lb
  connection: httpapi
  gather_facts: false

  vars:
    ansible_httpapi_password: "{{ ansible_password }}"
    ansible_network_os: f5networks.f5_bigip.bigip
    ansible_httpapi_use_ssl: true
    ansible_httpapi_validate_certs: false
    ansible_httpapi_port: "{{ server_port }}"
    ansible_command_timeout: 300
    ansible_httpapi_use_proxy: false


  tasks:

    - name: Use find to get the files list which you want to copy/fetch
      ansible.builtin.find:
        paths: /tmp/
        patterns: "*.ucs"
      register: ucs_fetch
      delegate_to: localhost

    - name: Upload UCS
      f5networks.f5_bigip.bigip_ucs:
        ucs: "{{ ucs_fetch.files[0].path }}"
        state: present
      register: restore_task_upload

    # - name: Run UCS Restore with Platform Migrate (via BIG-IP Command)
    #   f5networks.f5_bigip.bigip_command:
    #     commands: show sys version
    #     use_ssh: true
    #   register: restore_task
    #   ignore_errors: true

          # - "load /sys ucs {{ ucs_fetch.files[0].path.split('/')[2] }} no-license platform-migrate"


- name: Run Restore via SSH (Due to API Restarts)
  hosts: velos-lb
  become: false  # set to true if you need sudo
  tasks:

    - name: Find Local UCS File Name
      ansible.builtin.find:
        paths: /tmp/
        patterns: "*.ucs"
      register: ucs_fetch
      delegate_to: localhost

    - name: Run Restore Command with Platform-Migrate
      ansible.builtin.command: "tmsh load /sys ucs {{ ucs_fetch.files[0].path.split('/')[2] }} no-license platform-migrate"
      register: restore_task

    - name: Debug Output of Restore
      ansible.builtin.debug:
        var: restore_task

    - name: Pause for 5 Minutes
      ansible.builtin.pause:
        minutes: 5

- name: Wait for Restored F5 to Come Online
  hosts: velos-lb
  connection: httpapi
  gather_facts: false

  vars:
    ansible_httpapi_password: "{{ ansible_password }}"
    ansible_network_os: f5networks.f5_bigip.bigip
    ansible_httpapi_use_ssl: true
    ansible_httpapi_validate_certs: false
    ansible_httpapi_port: "{{ server_port }}"
    ansible_command_timeout: 300
    ansible_httpapi_use_proxy: false
  tasks:

    - name: Wait For Restore to Complete and system to become Active (15 Minutes of Retries)
      f5networks.f5_bigip.bigip_command:
        commands: show cm failover-status
      register: f5_online
      until:
        - f5_online is defined
        - "'stdout' in f5_online"
        - f5_online.stdout is iterable and f5_online.stdout | length > 0
        - "'ACTIVE' in f5_online.stdout[0]"
        - "'green' in f5_online.stdout[0]"
      retries: 30
      delay: 30
