---
- name: GRAB F5 FACTS
  hosts: lb
  connection: local
  gather_facts: false

  tasks:

    - name: Set Provider
      ansible.builtin.set_fact:
        provider:
          server: "{{ ansible_host }}"
          user: "{{ ansible_user }}"
          password: "{{ ansible_password }}"
          server_port: "{{ server_port }}"
          no_f5_teem: true
          validate_certs: false

    - name: Stop BIGSTART to Disable Node
      f5networks.f5_modules.bigip_command:
        commands: >
          run /util bash -c "bigstart stop"
        provider: "{{ provider }}"
      register: stop_task
      ignore_errors: true

    # - name: Debug
    #   ansible.builtin.debug:
    #     var: stop_task
