---
- name: GRAB F5 FACTS
  hosts: lb
  connection: local
  gather_facts: false

  tasks:

    - name: Stop BIGSTART to Disable Node
      f5networks.f5_modules.bigip_command:
        commands: >
          run /util bash -c "bigstart stop"
        provider: "{{ provider }}"
      register: stop_task

    - name: Debug
      ansible.builtin.debug:
        var: stop_task
