---

- name: Copy Inventory File For Tenant Creation
  hosts: bastion-backup
  tasks:

    - name: use find to get the files list which you want to copy/fetch
      ansible.builtin.find: 
        paths: /tmp/
        patterns: "*.ucs"
      register: UCS_fetch

    - name: use fetch to get the files #NEED TO FIX FOR SPECIFIC UCS FILE 
      ansible.builtin.fetch:
        src: "{{ item.path }}"
        dest: /tmp/
        flat: yes
      with_items: "{{ UCS_fetch.files }}"


- name: Restore UCS to Destination
  hosts: velos-lb
  connection: local
  gather_facts: false

  tasks:
    - name: Set Provider
      ansible.builtin.set_fact:
        provider:
          server: "{{ ansible_host }}"
          user: "{{ ansible_user }}"
          password: "{{ ansible_password }}"
          server_port: "{{ server_port }}"
          transport: cli
          no_f5_teem: yes
          validate_certs: false

    - name: use find to get the files list which you want to copy/fetch
      ansible.builtin.find: 
        paths: /tmp/
        patterns: "*.ucs"
      register: UCS_fetch
      delegate_to: localhost

    - name: Upload UCS
      f5networks.f5_modules.bigip_ucs:
        ucs: "{{ UCS_fetch.files[0].path }}"
        state: present
        provider: "{{ provider }}"
      register: restore_task_upload
      delegate_to: localhost

    - name: Run UCS Restore with Platform Migrate (via BIG-IP Command)
      f5networks.f5_modules.bigip_command:
        commands: >
          run /util bash -c "tmsh load /sys ucs {{ UCS_fetch.files[0].path.split('/')[2] }} no-license platform-migrate"
        provider: "{{ provider }}"
      register: restore_task
      ignore_errors: true
      delegate_to: localhost
      
          #- "load /sys ucs {{ UCS_fetch.files[0].path.split('/')[2] }} no-license platform-migrate"

    - name: Debug restore_task
      ansible.builtin.debug:
        var: restore_task

    # - name: Wait for Backup Task to complete
    #   ansible.builtin.uri:
    #     url: "https://{{ ansible_host }}/mgmt/tm/task/sys/ucs/{{ restore_task.task_id }}"
    #     method: GET
    #     return_content: true
    #     status_code: 200
    #     force_basic_auth: true
    #     user: "{{ ansible_user }}"
    #     password: "{{ ansible_password }}"
    #     validate_certs: false
    #   register: atc_Backup_status
    #   until: atc_Backup_status is success
    #   retries: 30
    #   delay: 30
    #   delegate_to: localhost
    #   when: task.changed
